In [123]:
import numpy as np
import pandas as pd

df=pd.read_csv('Ecommerce project.csv')
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    str
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), str(12)
memory usage: 61.5 KB

In [125]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [126]:
df.shape

(524, 15)

In [127]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [128]:
df.duplicated().sum()

np.int64(11)

In [129]:
#remove duplicate

df.drop_duplicates(inplace=True)

In [130]:
df.duplicated().sum()

np.int64(0)

In [131]:
#replace invalid value

df.replace(['N/A','NULL',' '],np.nan,inplace=True)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,NaN,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,NaN,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [132]:
#remove extra space
df=df.apply(lambda x: x.str.strip() if x.dtype=='str' else x)

In [133]:
#standardize text format
df['Customer_Name']=df['Customer_Name'].str.title()

df['City']=df['City'].str.title()

df['State']=df['State'].str.title()

In [134]:
#validate email addresses --keep only valid email

df=df[df['Email'].str.contains('@',na=False)]

In [135]:
#Convert date column

df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')
df['Delivery_Date']=pd.to_datetime(df['Delivery_Date'],errors='coerce')

C:\Users\admin\AppData\Local\Temp\ipykernel_16204\62388015.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')

In [136]:
#convert numeric columns

cols=['Qty','Unit_Price','Discount']

for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')

In [137]:
#Remove invalid quantity --Remove neative or zero quantity

df=df[df['Qty']>0]

In [138]:
#fill missing value
df['Discount']=df['Discount'].fillna(0)
df['Phone']=df['Phone'].fillna('Unknown')
df['Delivery_Date']=df['Delivery_Date'].fillna(df['Order_Date'])

In [139]:
#sales amount column
df['Sales']=df['Qty']*df['Unit_Price']
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-09-03,2997.0

In [140]:
#Net_amount column
df['Net_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.00
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0,19996.00
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0,5697.15
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.00
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.00
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-09-03,2997.0,2847.15

In [ ]:
#profit(20%) column
df['Profit']=df['Net_Amount']*0.20
df

In [ ]:
#order month,year,weekday
df['Month']=df['Order_Date'].dt.month_name()
df['Year']=df['Order_Date'].dt.year
df['Weekday']=df['Order_Date'].dt.day_name()
df

In [ ]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")
df.columns

In [ ]:
#Final data validation
df.info()

In [ ]:
df.isnull().sum() # we handle null value in power bi

In [ ]:
#export clean data
df.to_csv('Clean_Ecommerce.csv',index=False)

In [ ]:
from sqlalchemy import create_engine

username="postgres"
password="nitin123"
host="localhost"
port="5432"
database="Ecommerce_db"# database name you created in sql

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="ecommerce_sales"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"Data Successfully Loaded into table '{table_name}'in database'{database}'.")

In [ ]:
df.shape

In [ ]:
df